--Count the total_unique_products 

SELECT		
	COUNT(DISTINCT PRODUCT_NAME) AS TOTAL_UNIQUE_PRODUCTS
FROM
	FACT_PHARMA_INVENTORY;
--Total Capital Locked

SELECT
	SUM(QTY_ON_HAND * UNIT_COST) AS ABSOLUTE_TOTAL_VALUE
FROM
	FACT_PHARMA_INVENTORY;

--Inventory Value per Product (Top 10 Highest)

SELECT
	PRODUCT_NAME,
	SUM(QTY_ON_HAND * UNIT_COST) AS TOP_10_VALUE_PRODUCT
FROM
	FACT_PHARMA_INVENTORY
GROUP BY
	PRODUCT_NAME
ORDER BY
	TOP_10_VALUE_PRODUCT DESC
LIMIT
	10;